CREATE TABLE employee (
	sys_id INTEGER NOT NULL,
	emp_id INTEGER NOT NULL,
	first_name VARCHAR(20) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	rank INTEGER,
	PRIMARY KEY(sys_id)
	);

CREATE SEQUENCE sys_idgen
	START WITH 0
	INCREMENT BY 1
	MINVALUE 0;
	
CREATE SEQUENCE emp_idgen
	START WITH 0
	INCREMENT BY 1
	MINVALUE 0;