CREATE TABLE employee (
	sys_id NUMBER(5) NOT NULL,
	emp_id NUMBER(5) NOT NULL,
	first_name VARCHAR(20) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	rank NUMBER(5),
	PRIMARY KEY(sys_id)
	);

CREATE SEQUENCE sys_idgen
	START WITH 0
	INCREMENT BY 1
	MINVALUE 0;
	
CREATE SEQUENCE emp_idgen
	START WITH 0
	INCREMENT BY 1
	MINVALUE 0;